### ISSUE TITLE
Can't stop an input stream with stream.stop()

### ISSUE THREAD

**Issue by yilinwei** [djg/cubeb-rs#16]
I'm not too familiar with the cubeb library and have been trying to get the input functionality working; I'm seeing some behavior where calling `.stop()` blocks the calling thread until in the callback I explicitly return `0`. I've uploaded a [gist](https://gist.github.com/yilinwei/7ee42dc1616aaef24661f1630b3c2f6f).

Is this meant to be the correct behaviour?

**Comment by djg** [comment]
@kinetiknz can you comment here? I don't know the behaviour of backend well enough to answer. I know that stop() blocks till the backend is shutdown the stream but does that require the callback to return 0 to cause draining?

**Comment by kinetiknz** [comment]
`stop` should stop the stream.

I took the linked gist, modified it to always return `input.len()` and compiled it against the current cubeb-rs and it works as expected, i.e. there is not a large delay between the logging of "ATTEMPT STOP" and "STOPPED".  Maybe you ran into a bug that has since been fixed?
